version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: on-failure

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: unless-stopped
  
  server: 
    build: .
    image: trip-service:local
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./config:/app/config
    restart: on-failure

volumes:
  redis_data:
